# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('start_date', models.DateTimeField(verbose_name='date published')),
                ('end_date', models.DateTimeField(verbose_name='date published')),
                ('num_team', models.IntegerField(default=0)),
            ],
        ),
    ]
